# Generated by Django 5.0.3 on 2025-05-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('server', 'Server'), ('desktop', 'Desktop Computer'), ('laptop', 'Laptop'), ('mobile', 'Mobile Device'), ('iot', 'IoT Device'), ('printer', 'Printer'), ('camera', 'Camera'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='operating_system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='os_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='uptime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
