# Generated by Django 5.0.3 on 2025-05-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_monitor', '0002_device_device_type_device_manufacturer_device_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='device',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='device',
            name='model',
        ),
        migrations.RemoveField(
            model_name='device',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='device',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='device',
            name='os_version',
        ),
        migrations.RemoveField(
            model_name='device',
            name='uptime',
        ),
    ]
