# Generated by Django 5.0.1 on 2025-05-19 19:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_monitor', '0003_remove_device_device_type_remove_device_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanhistory',
            options={'ordering': ['-start_time'], 'verbose_name_plural': 'Scan Histories'},
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('new_device', 'New Device Detected'), ('status_change', 'Device Status Change'), ('port_change', 'Open Port Change'), ('security', 'Security Alert')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='device_monitor.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
