# Generated by Django 5.0.1 on 2025-05-19 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_monitor', '0004_alter_scanhistory_options_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'IP Whitelist Entry',
                'verbose_name_plural': 'IP Whitelist Entries',
                'ordering': ['ip_address'],
            },
        ),
    ]
